import { Metadata } from "next";
import "./globals.css";
import MarketplaceApp from "./ui/marketplaceApp";
import Techstack from "./ui/techstack";
import { ChevronDownIcon, CurrencyDollarIcon, EyeIcon, RocketLaunchIcon } from "@heroicons/react/24/outline";
import AwarenessText from "./ui/awareness-text";
import Hero from "./ui/hero";

export const metadata: Metadata = {
  title: "Symetria",
  description: "Generated by create next app",
};

const cardsText = [
  {
    id: 4,
    title: 'Access',
    desc: 'Make use of our services in a variety of payment models and bundles, find the services that best suit your needs and pay only for what you use.',
    icon: <CurrencyDollarIcon className="w-10 h-10 text-green-500" />
  },
  {
    id: 1,
    title: 'Optimize',
    desc: 'Speed up your processes with software that is performant and reliable. We build our services using cutting-edge software technologies.',
    icon: <RocketLaunchIcon className="w-10 h-10 text-green-500" />
  },
  {
    id: 2,
    title: 'Stand out',
    desc: 'Bring a satisfying experience to your customers with modern design and impressive user experience that boosts engagement and retention.',
    icon: <EyeIcon className="w-10 h-10 text-green-500" />
  },
]


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className='bg-black pb-22'>
        <Hero />

        <div className='w-full z-10 h-[200px] flex justify-center items-start py-10 mb-[200px]'>
          <ChevronDownIcon className="w-8 h-8 text-sym-text-primary animate-pulse" />
        </div>

        <AwarenessText />

        {/* Key points; Access, Optimize and Stand Out */}
        <div className="relative">

          <div className="absolute w-full h-full flex justify-center items-center z-20 bg-transparent">
            <div className="w-[1440px] h-[600px] grid grid-cols-3 gap-x-10">
              {
                cardsText.map((item) => (
                  <div key={item.id} className="col-span-1 w-full h-full flex flex-col justify-between py-12 px-10 bg-black rounded-[6px]">
                    <div className="flex flex-col gap-y-5">
                      <div className="flex items-center gap-x-5">
                        {
                          item.icon
                        }
                        <h1 className="text-sym-text-primary tracking-tight font-sym-title text-[3.2rem]">{item.title}</h1>
                      </div>
                      <p className="text-sym-text-secondary text-[1.4rem] text-balance">{item.desc}</p>
                    </div>
                    <button className="h-10 px-2 border border-sym-border hover:border-green-500 rounded-[6px] text-sym-text-primary hover:text-green-500 transition-color duration-300 capitalize animate-pulse hover:animate-none">Tell me More</button>
                  </div>
                ))
              }
            </div>
          </div>

          <div className="absolute w-full h-full glass -z-10"></div>

          <Techstack direction="right" />
          <Techstack direction="left" />
          <Techstack direction="right" />
          <Techstack direction="left" />
          <Techstack direction="right" />
          <Techstack direction="left" />
          <Techstack direction="right" />
          <Techstack direction="left" />
          <Techstack direction="right" />
          <Techstack direction="left" />

        </div>

        <div className="h-[200px]"></div>

        {/* Superior design part */}
        <section className="w-full flex justify-center">
          <div className="w-full max-w-[1440px]">
            <MarketplaceApp />
          </div>
        </section>

        {children}
      </body>
    </html>
  );
}
