import { Metadata } from "next";
import "./globals.css";
import IphoneCase from "./components/iphone-case";
import MobileMenu from "./components/mobile-menu";

export const metadata: Metadata = {
  title: "Symetria",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className=''
      >
        <IphoneCase size="sm">
          <div className="w-full h-full rounded-[15px]">
            <MobileMenu />
          </div>
        </IphoneCase>
        {children}
      </body>
    </html>
  );
}
